Repository cyralinc/approzium, pull requests merged in 2020-07, with the labels that each got.

#86 Create CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: enhancement

#87 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: testing/maintenance

#85 Improve server-side logging
  authenticator/Makefile
  authenticator/go.mod
  authenticator/go.sum
  authenticator/main.go
  authenticator/server/authenticator.go
  authenticator/server/authenticator_test.go
  authenticator/server/config.go
  authenticator/server/credmgrs/credmgr.go
  authenticator/server/credmgrs/local_file.go
  authenticator/server/identity/aws.go
  authenticator/server/identity/aws_test.go
  authenticator/server/identity/provider.go
  authenticator/server/protos/authenticator.pb.go
  authenticator/server/protos/authenticator.proto
  authenticator/server/requestlogger.go
  authenticator/server/testing/awsutil.go
  docs/src/pages/quickstart_.mdx
Labels: enhancement

#89 Add how to securely disclose vulnerabilities and get support
  README.md
Labels: testing/maintenance

#93 Improved protobufs by adding `PasswordRequest`
  authenticator/server/authenticator.go
  authenticator/server/authenticator_test.go
  authenticator/server/identity/provider.go
  authenticator/server/protos/authenticator.pb.go
  authenticator/server/protos/authenticator.proto
  authenticator/server/requestlogger.go
  sdk/python/Makefile
  sdk/python/approzium/_authenticator.py
  sdk/python/approzium/_protos/authenticator_pb2.py
  sdk/python/approzium/_protos/authenticator_pb2_grpc.py
Labels: enhancement

#91 Fix flaky test
  Makefile
Labels: testing/maintenance

#96 Add health endpoint and document HA
  authenticator/Makefile
  authenticator/go.mod
  authenticator/go.sum
  authenticator/main.go
  authenticator/server/api/api.go
  authenticator/server/api/health.go
  authenticator/server/api/health_test.go
  authenticator/server/authenticator.go
  authenticator/server/authenticator_test.go
  authenticator/server/config/config.go
  authenticator/server/config/config_test.go
  authenticator/server/health.go
  authenticator/server/protos/health.pb.go
  authenticator/server/protos/health.proto
  authenticator/server/testing/testutil.go
Labels: enhancement

#94 Add MySQL connector support
  Makefile
  authenticator/server/authenticator.go
  authenticator/server/authenticator_test.go
  authenticator/server/protos/authenticator.pb.go
  authenticator/server/protos/authenticator.proto
  authenticator/server/requestlogger.go
  authenticator/server/testing/secrets.yaml
  docker-compose.test.yml
  docker-compose.yml
  docs/src/pages/compatibility_.mdx
  sdk/python/approzium/_authenticator.py
  sdk/python/approzium/_mysql/__init__.py
  sdk/python/approzium/_protos/authenticator_pb2.py
  sdk/python/approzium/_protos/authenticator_pb2_grpc.py
  sdk/python/approzium/mysql/__init__.py
  sdk/python/approzium/mysql/connector/__init__.py
  sdk/python/approzium/mysql/connector/_connect.py
  sdk/python/approzium/mysql/connector/pooling.py
  sdk/python/docs/source/approzium.rst
  sdk/python/examples/mysql_connect.py
  sdk/python/examples/mysql_pool.py
  sdk/python/poetry.lock
  sdk/python/pyproject.toml
  sdk/python/tests/test_mysql_connect.py
Labels: enhancement

#95 Add server-side metrics with Prometheus support
  authenticator/Makefile
  authenticator/go.mod
  authenticator/go.sum
  authenticator/main.go
  authenticator/server/api/api.go
  authenticator/server/api/health.go
  authenticator/server/api/health_test.go
  authenticator/server/authenticator.go
  authenticator/server/authenticator_test.go
  authenticator/server/config.go
  authenticator/server/config/config.go
  authenticator/server/config/config_test.go
  authenticator/server/credmgrs/credmgr.go
  authenticator/server/credmgrs/hc_vault.go
  authenticator/server/credmgrs/hc_vault_test.go
  authenticator/server/credmgrs/local_file.go
  authenticator/server/health.go
  authenticator/server/identity/aws.go
  authenticator/server/identity/aws_test.go
  authenticator/server/identity/provider.go
  authenticator/server/metrics/registry.go
  authenticator/server/protos/health.pb.go
  authenticator/server/protos/health.proto
  authenticator/server/requestmetrics.go
  authenticator/server/testing/prometheus.txt
  authenticator/server/testing/testutil.go
  docs/doczrc.js
  docs/src/pages/configuration_.mdx
  docs/src/pages/languages/python.mdx
  docs/src/pages/observability_.mdx
  docs/src/pages/overview.mdx
  docs/src/pages/quickstart_.mdx
  sdk/python/approzium/_protos/authenticator_pb2.py
  sdk/python/approzium/_protos/authenticator_pb2_grpc.py
  sdk/python/approzium/asyncpg/_asyncpg_connect.py
  sdk/python/approzium/asyncpg/pool.py
  sdk/python/approzium/mysql/connector/_connect.py
  sdk/python/approzium/psycopg2/_psycopg2_connect.py
  sdk/python/approzium/psycopg2/pool.py
  sdk/python/examples/asyncpg_client.py
  sdk/python/examples/asyncpg_pool.py
  sdk/python/examples/mysql_connect.py
  sdk/python/examples/mysql_pool.py
  sdk/python/examples/pg2_client.py
  sdk/python/examples/pg2_pool.py
  sdk/python/tests/run_pg2_testsuite.py
  sdk/python/tests/test_asyncpg_connect.py
  sdk/python/tests/test_mysql_connect.py
  sdk/python/tests/test_psycopg2_connect.py
Labels: enhancement

#100 Improve Python SDK Docs
  sdk/python/approzium/_authenticator.py
  sdk/python/docs/source/api.rst
  sdk/python/docs/source/conf.py
  sdk/python/docs/source/examples.rst
  sdk/python/docs/source/index.rst
  sdk/python/docs/source/userguide.rst
  sdk/python/examples/asyncpg.py
  sdk/python/examples/asyncpg_client.py
  sdk/python/examples/asyncpg_pool.py
  sdk/python/examples/mysql_connect.py
  sdk/python/examples/mysql_connector.py
  sdk/python/examples/mysql_pool.py
  sdk/python/examples/pg2_client.py
  sdk/python/examples/pg2_pool.py
  sdk/python/examples/psycopg2.py
Labels: documentation

#101 Split CI workflow into test and lint workflows
  .github/workflows/lint.yml
  .github/workflows/main.yml
  .github/workflows/test.yml
  README.md
Labels: enhancement

#114 Replace approzium org with cyralinc
  README.md
  authenticator/go.mod
  authenticator/main.go
  authenticator/server/api/api.go
  authenticator/server/api/health.go
  authenticator/server/api/health_test.go
  authenticator/server/authenticator.go
  authenticator/server/authenticator_test.go
  authenticator/server/credmgrs/credmgr.go
  authenticator/server/health.go
  authenticator/server/identity/aws.go
  authenticator/server/identity/aws_test.go
  authenticator/server/identity/provider.go
  authenticator/server/requestlogger.go
  authenticator/server/requestmetrics.go
  docs/README.md
  docs/package.json
  docs/src/pages/languages/python.mdx
  docs/src/pages/quickstart_.mdx
  sdk/python/docs/source/index.rst
Labels: for patch release, testing/maintenance

#117 Create CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: for minor release, testing/maintenance

#110 Docasaurus
  .gitignore
  docs/.gitignore
  docs/Makefile
  docs/README.md
  docs/babel.config.js
  docs/docs/architecture.mdx
  docs/docs/compatibility.mdx
  docs/docs/configuration.mdx
  docs/docs/examples.mdx
  docs/docs/images/architecture-diagram.png
  docs/docs/images/overview-diagram.png
  docs/docs/observability.mdx
  docs/docs/overview.md
  docs/docs/quickstart.mdx
  docs/docs/roadmap.mdx
  docs/docs/security-model.mdx
  docs/docusaurus.config.js
  docs/doczrc.js
  docs/gatsby-config.js
  docs/gatsby-node.js
  docs/package.json
  docs/sidebars.js
  docs/src/css/custom.css
  docs/src/pages/404.js
  docs/src/pages/architecture_.mdx
  docs/src/pages/components/InfoModal/index.js
  docs/src/pages/components/InfoModal/styles.module.css
  docs/src/pages/index.js
  docs/src/pages/languages/go.mdx
  docs/src/pages/languages/python.mdx
  docs/src/pages/overview.mdx
  docs/src/pages/styles.module.css
  docs/src/theme/CodeBlock/index.js
  docs/src/theme/CodeBlock/styles.module.css
  docs/src/theme/Footer/index.js
  docs/src/theme/Footer/styles.module.css
  docs/src/theme/Navbar/index.js
  docs/src/theme/Navbar/styles.module.css
  docs/static/.nojekyll
  docs/static/img/apzm-icon.png
  docs/yarn.lock
Labels: for minor release

#111 Add support for TLS and dev mode
  Dockerfile
  authenticator/README.md
  authenticator/go.mod
  authenticator/go.sum
  authenticator/main.go
  authenticator/server/api/api.go
  authenticator/server/api/health.go
  authenticator/server/api/health_test.go
  authenticator/server/authenticator.go
  authenticator/server/authenticator_test.go
  authenticator/server/config/config.go
  authenticator/server/config/config_test.go
  authenticator/server/credmgrs/credmgr.go
  authenticator/server/credmgrs/local_file.go
  authenticator/server/health.go
  authenticator/server/protos/health.pb.go
  authenticator/server/protos/health.proto
  authenticator/server/testing/approzium.key
  authenticator/server/testing/approzium.pem
  authenticator/server/testing/ca.cert
  authenticator/server/testing/ca.key
  authenticator/server/testing/client.key
  authenticator/server/testing/client.pem
  docker-compose.test.yml
  docker-compose.yml
  docs/docs/configuration.mdx
  docs/docs/examples.mdx
  docs/docs/observability.mdx
  docs/docs/quickstart.mdx
  sdk/python/approzium/__init__.py
  sdk/python/approzium/_authenticator.py
  sdk/python/approzium/mysql/connector/_connect.py
  sdk/python/examples/asyncpg_connect.py
  sdk/python/examples/mysql_connector_connect.py
  sdk/python/examples/psycopg2_connect.py
  sdk/python/tests/conftest.py
Labels: enhancement, for minor release

#141 Add --version and --dev flags
  authenticator/Makefile
  authenticator/README.md
  authenticator/main.go
  authenticator/server/config/config.go
  authenticator/server/config/config_test.go
Labels: enhancement, for minor release

#140 add small logo, update home page title
  docs/src/pages/index.js
  docs/static/img/apzm-icon-s.png
Labels: documentation

#147 Fix non-TLS Connection to Authenticator
  sdk/python/approzium/_authenticator.py
  sdk/python/examples/psycopg2_connect.py
Labels: for patch release

#149 Link to Cyral
  docs/docusaurus.config.js
  docs/src/theme/Footer/index.js
Labels: documentation

#148 Add Support for PyMySQL
  docs/docs/compatibility.mdx
  sdk/python/approzium/_misc.py
  sdk/python/approzium/_mysql/__init__.py
  sdk/python/approzium/mysql/connector/_connect.py
  sdk/python/approzium/pymysql/__init__.py
  sdk/python/approzium/pymysql/_connect.py
  sdk/python/docs/source/api.rst
  sdk/python/docs/source/examples.rst
  sdk/python/docs/source/userguide.rst
  sdk/python/examples/pymysql_connect.py
  sdk/python/poetry.lock
  sdk/python/pyproject.toml
  sdk/python/tests/test_mysql_connector_connect.py
  sdk/python/tests/test_pymysql_connect.py
Labels: enhancement, for minor release

#151 unitalicize keywords in code blocks
  docs/src/theme/CodeBlock/index.js
Labels: documentation

#156 docs: Add GitHub Security Policy
  .github/SECURITY.md
  README.md
Labels: documentation

#157 Fix TLS flag
  authenticator/server/config/config.go
Labels: bug, for patch release

#150 Add Support for AWS Secrets Manager
  .github/workflows/test.yml
  Dockerfile
  Makefile
  authenticator/approzium.config.yml
  authenticator/server/authenticator.go
  authenticator/server/config/config.go
  authenticator/server/credmgrs/aws_secrets_manager.go
  authenticator/server/credmgrs/aws_secrets_manager_test.go
  authenticator/server/credmgrs/credmgr.go
  authenticator/server/credmgrs/hc_vault.go
  authenticator/server/credmgrs/hc_vault_test.go
  authenticator/server/credmgrs/local_file.go
  authenticator/server/testing/awsutil.go
  docker-compose.test.yml
  docker-compose.yml
  docs/docs/compatibility.mdx
  docs/docs/configuration.mdx
  docs/docs/quickstart.mdx
  docs/docs/roadmap.mdx
  sdk/python/tests/conftest.py
Labels: enhancement, for minor release

#123 Add Opentelemetry Integration to Python SDK
  .readthedocs.yml
  Dockerfile
  docker-compose.yml
  sdk/python/approzium/_authenticator.py
  sdk/python/approzium/_iam.py
  sdk/python/approzium/asyncpg/_asyncpg_connect.py
  sdk/python/approzium/mysql/connector/_connect.py
  sdk/python/approzium/opentelemetry/__init__.py
  sdk/python/approzium/psycopg2/_psycopg2_connect.py
  sdk/python/docs/source/api.rst
  sdk/python/docs/source/examples.rst
  sdk/python/examples/asyncpg_connect.py
  sdk/python/examples/mysql_connector_connect.py
  sdk/python/examples/psycopg2_attribution_info.py
  sdk/python/examples/psycopg2_opentelemetry.py
  sdk/python/poetry.lock
  sdk/python/pyproject.toml
Labels: enhancement, for minor release

#165 Clarify Docs for Installing Database Drivers Alongside SDK
  docs/docs/quickstart.mdx
  sdk/python/docs/source/userguide.rst
Labels: documentation

#163 Give direct authenticator instructions
  docs/docs/quickstart.mdx
Labels: documentation

#166 Release/0.1.2
  authenticator/server/config/config.go
  sdk/python/approzium/_authenticator.py
  sdk/python/approzium/_socketfromfd.py
  sdk/python/approzium/psycopg2/_psycopg2_ctypes.py
  sdk/python/examples/psycopg2_connect.py
  sdk/python/poetry.lock
Labels: release

#167 Add convenience script for generating shas
  authenticator/scripts/getshas.sh
Labels: testing/maintenance
